import {
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
  integer,
  pgEnum,
} from "drizzle-orm/pg-core";

// Enum for decision status lifecycle
export const decisionStatusEnum = pgEnum("decision_status", [
  "active",
  "exited",
  "monitoring",
]);

// Users - synced from Clerk
export const users = pgTable("users", {
  id: varchar("id", { length: 256 }).primaryKey(), // Clerk user ID
  email: varchar("email", { length: 256 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Decisions (investment decisions / journal entries)
export const decisions = pgTable("decisions", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: varchar("user_id", { length: 256 })
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  // Core thesis
  title: varchar("title", { length: 512 }).notNull(), // e.g. "Long NVDA", "Seed Acme Inc"
  thesis: text("thesis").notNull(), // free-text: why you're making this bet
  keyAssumptions: text("key_assumptions"), // JSON array of assumption strings
  expectedOutcome: text("expected_outcome"), // what success looks like
  expectedTimeline: varchar("expected_timeline", { length: 256 }), // e.g. "12 months"

  // Pre-mortem prompt answer
  premortemAnswer: text("premortem_answer"), // if this fails in 12 months, why?

  // Status
  status: decisionStatusEnum("status").default("active").notNull(),

  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Thesis challenges generated by AI
export const thesisChallenges = pgTable("thesis_challenges", {
  id: uuid("id").defaultRandom().primaryKey(),
  decisionId: uuid("decision_id")
    .notNull()
    .references(() => decisions.id, { onDelete: "cascade" }),

  // AI-generated content
  strongestCounterArguments: text("strongest_counter_arguments").notNull(), // JSON array
  implicitAssumptions: text("implicit_assumptions").notNull(), // JSON array
  clarifyingQuestion: text("clarifying_question").notNull(), // single question

  // User feedback on challenge quality
  qualityRating: integer("quality_rating"), // 1–5

  createdAt: timestamp("created_at").defaultNow().notNull(),
});
